### ISSUE TITLE
BombitUP SMS blast not working 

### ISSUE THREAD

**Issue by Raxy45** [romreviewer/BOMBitUP#17]
Currently , I'm using BombitUP APK version 4.2 and whenever I type the phone number it only shows up "verifying number please wait" and doesn't go ahead of this step . Hope the issue will be resolved :p

**Comment by kksksmsk** [comment]
My bombit app is not working

**Comment by Raxy45** [comment]
The issue's resolved and BombItUP's up and running, Thanks :p, closing the issue !

**Comment by BlrxRama** [comment]
Yes, my Bombitup is Also not working
